language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: undesirable-lunchroom.surge.sh
  project: ./build/
on:
  branch: master