language: node_js
node_js:
  - "stable"
# cache:
#   directories:
#     - node_modules
script:
  - yarn install
  - yarn test
  - yarn run build
  
deploy:
  provider: surge
  domain: undesirable-lunchroom.surge.sh
  project: ./build/
on:
  branch: master